In [7]:
import pandas as pd

In [8]:
df=pd.read_csv("tmdb-movies.csv")
df.head()

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,...,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/15,5562,6.5,2015,1.379999e+08,1.392446e+09
1,76341,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,What a Lovely Day.,...,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/15,6185,7.1,2015,1.379999e+08,3.481613e+08
2,262500,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,One Choice Can Destroy You,...,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/15,2480,6.3,2015,1.012000e+08,2.716190e+08
3,140607,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Every generation has a story.,...,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/15,5292,7.5,2015,1.839999e+08,1.902723e+09
4,168259,tt2820852,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,Vengeance Hits Home,...,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/15,2947,7.3,2015,1.747999e+08,1.385749e+09

In [9]:
df.describe()

,id,popularity,budget,revenue,runtime,vote_count,vote_average,release_year,budget_adj,revenue_adj
count,10866.000000,10866.000000,1.086600e+04,1.086600e+04,10866.000000,10866.000000,10866.000000,10866.000000,1.086600e+04,1.086600e+04
mean,66064.177434,0.646441,1.462570e+07,3.982332e+07,102.070863,217.389748,5.974922,2001.322658,1.755104e+07,5.136436e+07
std,92130.136561,1.000185,3.091321e+07,1.170035e+08,31.381405,575.619058,0.935142,12.812941,3.430616e+07,1.446325e+08
min,5.000000,0.000065,0.000000e+00,0.000000e+00,0.000000,10.000000,1.500000,1960.000000,0.000000e+00,0.000000e+00
25%,10596.250000,0.207583,0.000000e+00,0.000000e+00,90.000000,17.000000,5.400000,1995.000000,0.000000e+00,0.000000e+00
50%,20669.000000,0.383856,0.000000e+00,0.000000e+00,99.000000,38.000000,6.000000,2006.000000,0.000000e+00,0.000000e+00
75%,75610.000000,0.713817,1.500000e+07,2.400000e+07,111.000000,145.750000,6.600000,2011.000000,2.085325e+07,3.369710e+07
max,417859.000000,32.985763,4.250000e+08,2.781506e+09,900.000000,9767.000000,9.200000,2015.000000,4.250000e+08,2.827124e+09

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10866 entries, 0 to 10865
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    10866 non-null  int64
 1   imdb_id               10856 non-null  object
 2   popularity            10866 non-null  float64
 3   budget                10866 non-null  int64
 4   revenue               10866 non-null  int64
 5   original_title        10866 non-null  object
 6   cast                  10790 non-null  object
 7   homepage              2936 non-null   object
 8   director              10822 non-null  object
 9   tagline               8042 non-null   object
 10  keywords              9373 non-null   object
 11  overview              10862 non-null  object
 12  runtime               10866 non-null  int64
 13  genres                10843 non-null  object
 14  production_companies  9836 non-null   object
 15  release_date          10866 non-null  object
 16  vote_count            10866 non-null  int64
 17  vote_average          10866 non-null  float64
 18  release_year          10866 non-null  int64
 19  budget_adj            10866 non-null  float64
 20  revenue_adj           10866 non-null  float64
dtypes: float64(4), int64(6), object(11)
memory usage: 1.7+ MB

In [27]:
df.columns

Index(['id', 'imdb_id', 'popularity', 'budget', 'revenue', 'original_title',
       'cast', 'homepage', 'director', 'tagline', 'keywords', 'overview',
       'runtime', 'genres', 'production_companies', 'release_date',
       'vote_count', 'vote_average', 'release_year', 'budget_adj',
       'revenue_adj'],
      dtype='object')

In [28]:
df1=df[['budget', 'revenue', 'original_title',
       'cast','runtime', 'genres', 'production_companies','release_year', 'budget_adj',
        'revenue_adj']]

In [29]:
df1=df1.dropna()

In [30]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9792 entries, 0 to 10865
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                9792 non-null   int64
 1   revenue               9792 non-null   int64
 2   original_title        9792 non-null   object
 3   cast                  9792 non-null   object
 4   runtime               9792 non-null   int64
 5   genres                9792 non-null   object
 6   production_companies  9792 non-null   object
 7   release_year          9792 non-null   int64
 8   budget_adj            9792 non-null   float64
 9   revenue_adj           9792 non-null   float64
dtypes: float64(2), int64(4), object(4)
memory usage: 841.5+ KB

In [31]:
#QUESTION NO: 1
# movies with the third lowest and third highest budget?

In [32]:
third_highest_budget=df1.sort_values(by='budget_adj',ascending=False)
third_lowest_budget=df1.sort_values(by='budget_adj')
print("third highest budget film:",third_highest_budget.iloc[2,2])
print("third lowest budget film:",third_lowest_budget.iloc[2,2])

third highest budget film: Pirates of the Caribbean: At World's End
third lowest budget film: Best of the Best

In [33]:
third_highest_budget[['original_title','budget_adj']].head(3) #order of budget is in descending order

                                   original_title    budget_adj
2244                            The Warrior's Way  4.250000e+08
3375  Pirates of the Caribbean: On Stranger Tides  3.683713e+08
7387     Pirates of the Caribbean: At World's End  3.155006e+08

In [34]:
third_lowest_budget[['original_title','budget_adj']].head(5) #order of budget is in ascending order

                original_title  budget_adj
9274           Field of Dreams         0.0
3584  Martha Marcy May Marlene         0.0
9214          Best of the Best         0.0
3582          That's What I Am         0.0
6001  The Jeffrey Dahmer Files         0.0

In [35]:
#QUESTION NO: 2
#Which are the movies with most and least earned revenue?

In [36]:
highest_revenue=df1.sort_values(by='revenue_adj',ascending=False)
lowest_revenue=df1.sort_values(by='revenue_adj')
print("highest revenue film:",highest_revenue.iloc[0,2])
print("lowest revenue film:",lowest_revenue.iloc[0,2])

highest revenue film: Avatar
lowest revenue film: Manos: The Hands of Fate

In [37]:
#QUESTION NO: 3
#What is the average runtime of movies in the year 2006?

In [38]:
average_run_time=df1.loc[(df1['release_year'] == 2006)]
avg=average_run_time['runtime'].mean()
print("average runtime of movies released in the year 2006 is:",avg)

average runtime of movies released in the year 2006 is: 101.93714285714286

In [39]:
#question no:4
# What is the average number of words in movie titles between the year 2000-2005?
movies=df1.loc[(df1['release_year']>=2000 ) & (df1['release_year']<=2005)]
number_of_words={}
for i in range(movies.shape[0]):
    words=str(movies['original_title'].values[i]).split(' ')
    for j in words:
        try:
            count=number_of_words[j]
            number_of_words[j]=count+1
        except:
            number_of_words[j]=1
            
number_of_words

{'The': 317,
 'Lord': 6,
 'of': 152,
 'the': 152,
 'Rings:': 3,
 'Fellowship': 1,
 'Ring': 5,
 'Harry': 5,
 'Potter': 4,
 'and': 45,
 "Philosopher's": 1,
 'Stone': 4,
 'Mulholland': 1,
 'Drive': 1,
 'Donnie': 1,
 'Darko': 1,
 'Monsters,': 1,
 'Inc.': 1,
 'A.I.': 1,
 'Artificial': 1,
 'Intelligence': 1,
 'Shrek': 3,
 'Bridget': 2,
 "Jones's": 1,
 'Diary': 2,
 "Ocean's": 2,
 'Eleven': 2,
 'Pearl': 3,
 'Harbor': 1,
 'Mummy': 1,
 'Returns': 1,
 'Atlantis:': 2,
 'Lost': 10,
 'Empire': 1,
 'Lara': 2,
 'Croft:': 1,
 'Tomb': 2,
 'Raider': 1,
 'A': 23,
 'Beautiful': 1,
 'Mind': 3,
 'American': 10,
 'Pie': 2,
 '2': 32,
 'Princess': 4,
 'Diaries': 2,
 'Moulin': 1,
 'Rouge!': 1,
 'Planet': 5,
 'Apes': 1,
 'Royal': 2,
 'Tenenbaums': 1,
 'Blow': 2,
 'Enemy': 2,
 'at': 5,
 'Gates': 2,
 'Black': 9,
 'Hawk': 1,
 'Down': 8,
 'Legally': 2,
 'Blonde': 3,
 "Knight's": 1,
 'Tale': 2,
 'Zoolander': 1,
 'Not': 1,
 'Another': 2,
 'Teen': 1,
 'Movie': 18,
 'Scary': 3,
 'Rush': 1,
 'Hour': 4,
 'Training': 1,
 'Day': 7,
 'Others': 1,
 'Jimmy': 1,
 'Neutron:': 1,
 'Boy': 4,
 'Genius': 2,
 'Jay': 1,
 'Silent': 1,
 'Bob': 2,
 'Strike': 1,
 'Back': 7,
 'Serendipity': 1,
 'Cats': 1,
 '&': 26,
 'Dogs': 3,
 'Vanilla': 1,
 'Sky': 3,
 "Mike's": 1,
 'New': 8,
 'Car': 1,
 'Kiss': 3,
 'Dragon': 3,
 'Spy': 5,
 'Game': 3,
 'Swordfish': 1,
 'Shallow': 2,
 'Hal': 1,
 'Barbie': 4,
 'in': 37,
 'Nutcracker': 1,
 'Lady': 1,
 'Tramp': 1,
 'II:': 9,
 "Scamp's": 1,
 'Adventure': 5,
 'AntiTrust': 1,
 'Final': 5,
 'Fantasy:': 1,
 'Spirits': 1,
 'Within': 1,
 'Waking': 1,
 'Life': 15,
 'Original': 1,
 'Sin': 2,
 'Dr.': 2,
 'Dolittle': 1,
 'Behind': 3,
 'Lines': 1,
 'Jeepers': 2,
 'Creepers': 2,
 'Kate': 1,
 'Leopold': 1,
 "America's": 1,
 'Sweethearts': 1,
 'From': 2,
 'Hell': 2,
 'Last': 6,
 'Castle': 3,
 'Along': 2,
 'Came': 2,
 'a': 22,
 'Spider': 2,
 'Super': 2,
 'Troopers': 2,
 'Wedding': 5,
 'Planner': 1,
 'Rat': 1,
 'Race': 1,
 'Gosford': 1,
 'Park': 4,
 'Jason': 2,
 'X': 2,
 'Mexican': 1,
 'Joy': 1,
 'Ride': 1,
 'I': 10,
 'Am': 1,
 'Sam': 1,
 'Hole': 1,
 'Replicant': 1,
 'Tremors': 2,
 '3:': 4,
 'to': 30,
 'Perfection': 1,
 'One': 3,
 'Night': 3,
 "McCool's": 1,
 'Rock': 3,
 'Star': 7,
 'K-PAX': 1,
 'Someone': 1,
 'Like': 6,
 'You...': 1,
 'Dry': 1,
 "Don't": 4,
 'Say': 2,
 'Word': 1,
 'Thir13en': 1,
 'Ghosts': 3,
 'Crocodile': 2,
 'Dundee': 1,
 'Los': 3,
 'Angeles': 1,
 'Frailty': 1,
 "Mickey's": 2,
 'Magical': 1,
 'Christmas:': 1,
 'Snowed': 1,
 'House': 14,
 'Mouse': 1,
 'Angel': 2,
 'Eyes': 1,
 'as': 2,
 'Shipping': 1,
 'News': 2,
 'Hearts': 1,
 'Atlantis': 1,
 'Ghost': 3,
 'World': 8,
 'Glass': 2,
 '15': 1,
 'Minutes': 1,
 'O': 2,
 'Hardball': 1,
 'Evolution': 1,
 'Get': 3,
 'Over': 3,
 'It': 9,
 'Heartbreakers': 1,
 'Ali': 2,
 'Band': 2,
 'Brothers': 3,
 'Session': 1,
 '9': 3,
 'Score': 2,
 "Monster's": 1,
 'Ball': 1,
 'Joe': 2,
 'Dirt': 1,
 'Land': 5,
 'Before': 5,
 'Time': 10,
 'VIII:': 1,
 'Big': 13,
 'Freeze': 1,
 'Exit': 1,
 'Wounds': 1,
 'Tailor': 1,
 'Panama': 1,
 'Sweet': 3,
 'November': 1,
 'How': 4,
 'High': 6,
 'Earth': 2,
 'Tomcats': 1,
 'Elling': 1,
 'Majestic': 1,
 '3000': 3,
 'Miles': 1,
 'Graceland': 1,
 'Mists': 1,
 'Avalon': 1,
 'Tape': 1,
 'Wishmaster': 2,
 'Beyond': 3,
 "What's": 1,
 'Worst': 1,
 'That': 3,
 'Could': 2,
 'Happen?': 1,
 'Dil': 1,
 'Chahta': 1,
 'Hai': 1,
 'Mars': 2,
 'Saving': 2,
 'Silverman': 1,
 'Curse': 3,
 'Jade': 1,
 'Scorpion': 2,
 'Riding': 2,
 'Cars': 1,
 'with': 11,
 'Boys': 7,
 'Mimic': 1,
 'Osmosis': 1,
 'Jones': 1,
 'Man': 16,
 'Who': 3,
 "Wasn't": 1,
 'There': 2,
 'Buffalo': 1,
 'Soldiers': 4,
 'Head': 3,
 'Heels': 1,
 'Enigma': 1,
 'Fast': 4,
 'Furious': 3,
 'Human': 3,
 'Nature': 1,
 'Save': 1,
 'Dance': 2,
 'Affair': 1,
 'Necklace': 1,
 'Bully': 1,
 'Zebra': 1,
 'Lounge': 1,
 'In': 11,
 'Bedroom': 1,
 'Kids': 3,
 'Pledge': 1,
 'Mean': 3,
 'Machine': 2,
 'Bandits': 1,
 'Animal': 1,
 'Knockaround': 1,
 'Guys': 2,
 'Just': 4,
 'Visiting': 1,
 'Crazy/Beautiful': 1,
 'Safar': 1,
 'e': 2,
 'Ghandehar': 1,
 'Driven': 1,
 'Out': 4,
 'Cold': 5,
 'Citizen': 1,
 'Toxie:': 1,
 'Toxic': 1,
 'Avenger': 1,
 'IV': 1,
 'Thieves': 1,
 'Outlaws': 1,
 'Hannibal': 1,
 'Domestic': 1,
 'Disturbance': 1,
 'Unsaid': 1,
 'Birthday': 1,
 'Girl': 9,
 'Me': 11,
 'Without': 3,
 'You': 10,
 'Impostor': 1,
 'Parole': 1,
 'Officer': 1,
 'Lantana': 1,
 "Elvira's": 1,
 'Haunted': 3,
 'Hills': 1,
 'Texas': 2,
 'Rangers': 2,
 'Charlotte': 1,
 'Gray': 1,
 "Beethoven's": 2,
 '4th': 1,
 'Summer': 2,
 'Catch': 3,
 'Wet': 1,
 'Hot': 2,
 'Valentine': 1,
 'Heist': 1,
 'Believer': 1,
 'Max': 2,
 "Keeble's": 1,
 'Move': 1,
 'Monkeybone': 1,
 'See': 1,
 'Spot': 1,
 'Run': 4,
 'Storytelling': 1,
 '61*': 1,
 'Attila': 1,
 'Fourth': 1,
 'Corky': 1,
 'Romano': 1,
 'Somebody': 1,
 'To': 2,
 'End': 4,
 'All': 9,
 'Wars': 2,
 'Snow': 3,
 'White': 7,
 'Iris': 1,
 'Knight': 1,
 'Sued': 1,
 'God': 2,
 'Wit': 1,
 'Scooby-Doo': 3,
 'Cyber': 1,
 'Chase': 1,
 'Jurassic': 1,
 'III': 3,
 'Grey': 1,
 'Zone': 1,
 'Josie': 1,
 'Pussycats': 1,
 'Captain': 2,
 "Corelli's": 1,
 'Mandolin': 1,
 'Body': 1,
 'Order': 2,
 'James': 1,
 'Dean': 1,
 'Freddy': 2,
 'Got': 1,
 'Fingered': 1,
 'Epoch': 1,
 'Swamp': 1,
 'Karaoke': 1,
 'Party': 6,
 'Kissing': 1,
 'Jessica': 1,
 'Stein': 1,
 'Stanley': 1,
 'Kubrick:': 1,
 'Pictures': 1,
 'Le': 9,
 'vÃ©lo': 1,
 'de': 6,
 'Ghislain': 1,
 'Lambert': 1,
 'Musketeer': 1,
 "Cat's": 1,
 'Meow': 1,
 'Forsaken': 1,
 "Isn't": 1,
 'So': 2,
 'Bubble': 2,
 'Blue': 5,
 'Conspiracy': 1,
 'Novocaine': 1,
 'Sugar': 1,
 'Spice': 1,
 'Bones': 1,
 'Dogtown': 2,
 'Z-Boys': 1,
 'CQ': 1,
 'Anniversary': 1,
 'Wash': 1,
 'Made': 2,
 'Butterflies': 1,
 'Halloweentown': 2,
 "Kalabar's": 1,
 'Revenge': 2,
 'Children': 3,
 'Corn:': 1,
 'Revelation': 1,
 'Holiday': 1,
 'Sun': 4,
 'BelphÃ©gor': 1,
 '-': 6,
 'fantÃ´me': 1,
 'du': 2,
 'Louvre': 1,
 'Delirious': 1,
 'Baby': 3,
 'Tanguy': 1,
 'Double': 1,
 'Take': 1,
 'Two': 4,
 'Towers': 1,
 'Chamber': 1,
 'Secrets': 2,
 'Ice': 3,
 'Age': 1,
 'Bourne': 2,
 'Identity': 2,
 'Resident': 2,
 'Evil': 2,
 'Spider-Man': 2,
 'Wars:': 2,
 'Episode': 2,
 'II': 11,
 'Attack': 2,
 'Clones': 1,
 'If': 4,
 'Can': 2,
 'Men': 3,
 'Pianist': 1,
 'Minority': 1,
 'Report': 1,
 'Lilo': 2,
 'Stitch': 3,
 'Transporter': 2,
 'xXx': 1,
 'Treasure': 2,
 'Die': 5,
 '28': 2,
 'Days': 8,
 'Later...': 1,
 'Maid': 1,
 'Manhattan': 2,
 'Blade': 1,
 'Gangs': 1,
 'York': 3,
 'Panic': 1,
 'Room': 4,
 'Stuart': 2,
 'Little': 11,
 'National': 4,
 'Lampoonâ€™s': 1,
 'Van': 3,
 'Wilder': 1,
 '8': 1,
 'Mile': 2,
 'Mr.': 3,
 'Deeds': 1,
 'Bend': 1,
 'Beckham': 1,
 'Cinderella': 3,
 'Dreams': 3,
 'Come': 2,
 'True': 3,
 'Weeks': 1,
 'Notice': 1,
 'Signs': 1,
 'Home': 4,
 'Alone': 3,
 '4': 1,
 'Walk': 2,
 'Remember': 2,
 'My': 7,
 'Fat': 3,
 'Greek': 1,
 'About': 7,
 'Hunchback': 1,
 'Notre': 1,
 'Dame': 1,
 'Collateral': 2,
 'Damage': 1,
 'Phone': 1,
 'Booth': 1,
 'Trek:': 1,
 'Nemesis': 1,
 'Equilibrium': 1,
 'Good': 7,
 'Hours': 1,
 'Road': 3,
 'Perdition': 1,
 'Austin': 1,
 'Powers': 1,
 'Goldmember': 1,
 'Santa': 2,
 'Clause': 1,
 'Insomnia': 1,
 'Ship': 1,
 'Tuxedo': 1,
 'Spirit:': 1,
 'Stallion': 2,
 'Cimarron': 1,
 'D-Tox': 1,
 'Secretary': 1,
 'King': 7,
 'Bowling': 1,
 'for': 8,
 'Columbine': 1,
 '25th': 1,
 'Ken': 1,
 'Tarzan': 2,
 'Jane': 2,
 'Sum': 1,
 'Fears': 1,
 '51st': 1,
 'State': 5,
 'We': 6,
 'Were': 1,
 'Jackass:': 1,
 'Chick': 1,
 'Frida': 1,
 'Murder': 1,
 'by': 3,
 'Numbers': 2,
 'Adaptation.': 1,
 'Alabama': 1,
 'Barbershop': 2,
 'Dark': 6,
 'Undisputed': 1,
 'Sweetest': 1,
 'Thing': 4,
 'Guru': 1,
 'Windtalkers': 1,
 'John': 3,
 'Q': 1,
 '40': 3,
 'Nights': 3,
 'Rapunzel': 1,
 'Unfaithful': 1,
 'Changing': 1,
 'Lanes': 1,
 'Punch-Drunk': 1,
 'Love': 12,
 'K-19:': 1,
 'Widowmaker': 1,
 'Eight': 2,
 'Legged': 1,
 'Freaks': 1,
 'Cube': 2,
 '2:': 13,
 'Hypercube': 1,
 'Queen': 2,
 'Damned': 1,
 'Island': 2,
 'IX:': 1,
 'Journey': 2,
 'Water': 5,
 'Enough': 1,
 'Friday': 5,
 'After': 4,
 'Next': 4,
 'Return': 8,
 'Never': 2,
 'Nicholas': 1,
 'Nickleby': 1,
 'or': 3,
 'Something': 2,
 'Slackers': 1,
 'Sorority': 1,
 'Interstate': 1,
 '60': 1,
 'Chicago': 2,
 'Photo': 1,
 'Femme': 1,
 'Fatale': 1,
 'Crazy': 1,
 'City': 4,
 'By': 2,
 'Sea': 4,
 'G': 1,
 'Indahouse': 1,
 'Darkness': 2,
 'Reign': 1,
 'Fire': 4,
 'Showtime': 1,
 'S1m0ne': 1,
 'Crimes': 1,
 'Moonlight': 1,
 "Hart's": 1,
 'War': 4,
 'Schmidt': 1,
 'Crush': 1,
 'Blood': 2,
 'Work': 1,
 'Solaris': 1,
 'Banger': 1,
 'Sisters': 2,
 'Four': 3,
 'Feathers': 1,
 'Quiet': 2,
 'Balto': 2,
 'Wolf': 2,
 'Quest': 2,
 'Magdalene': 1,
 'Guy': 4,
 'Mothman': 1,
 'Prophecies': 1,
 'Far': 2,
 'from': 4,
 'Heaven': 5,
 'Rookie': 1,
 'Bad': 4,
 'Company': 3,
 'Sniper': 2,
 'Confessions': 3,
 'Dangerous': 2,
 'Rules': 3,
 'Attraction': 2,
 'Eye': 2,
 'Hellraiser:': 4,
 'Hellseeker': 1,
 'Killing': 1,
 'Softly': 1,
 'Taken': 1,
 'Ballistic:': 1,
 'Ecks': 1,
 'vs.': 3,
 'Sever': 1,
 'Analyze': 1,
 'Trapped': 1,
 'Derailed': 2,
 'Hollywood': 3,
 'Ending': 1,
 'Spun': 1,
 'Clockstoppers': 1,
 'Halloween:': 1,
 'Resurrection': 2,
 'Salton': 1,
 'Dog': 2,
 'on': 7,
 'Turk': 1,
 'Street': 1,
 'Liar': 1,
 'Count': 2,
 'Monte': 1,
 'Cristo': 1,
 'Narc': 1,
 'Space': 4,
 'Station': 2,
 '3D': 1,
 'Rollerball': 1,
 'They': 1,
 'Skulls': 2,
 'Nothing': 1,
 'Gone': 2,
 'Nutty': 2,
 'Divine': 1,
 'Ya-Ya': 1,
 'Sisterhood': 2,
 'Antwone': 1,
 'Fisher': 1,
 'Try': 1,
 'Seventeen': 1,
 '24': 1,
 'People': 2,
 'Babylon': 1,
 '5:': 1,
 'Legend': 7,
 'Live': 3,
 'Starlight': 1,
 'Cadet': 1,
 'Kelly': 3,
 'Igby': 1,
 'Goes': 1,
 'Liberty': 2,
 'Stands': 1,
 'Still': 1,
 'Swept': 1,
 'Away': 2,
 'Rabbit-Proof': 1,
 'Fence': 1,
 'Boat': 1,
 'Trip': 3,
 'Oleander': 1,
 'May': 1,
 'Crossroads': 1,
 'Adventures': 3,
 'Pluto': 1,
 'Nash': 1,
 'Abandon': 1,
 'Firestarter': 1,
 'Rekindled': 1,
 'Long': 3,
 'Dead': 13,
 'Deathwatch': 1,
 'Red': 4,
 'Laurel': 1,
 'Canyon': 1,
 'Serving': 1,
 'Sara': 1,
 'Bloody': 2,
 'Sunday': 1,
 'Tom': 2,
 'Jerry:': 2,
 'Magic': 4,
 'Dragonfly': 1,
 'Shottas': 1,
 'Drumline': 1,
 'Importance': 1,
 'Being': 1,
 'Earnest': 1,
 'Mike': 1,
 'Gerry': 1,
 'Rose': 3,
 'Lives': 2,
 'Altar': 1,
 'Hey': 1,
 'Arnold!': 1,
 'Carrie': 1,
 "Emperor's": 2,
 'Club': 2,
 'Half': 1,
 'Past': 1,
 'Welcome': 2,
 'Collinwood': 1,
 'Dirty': 5,
 'Pretty': 3,
 'Things': 4,
 'K-9:': 1,
 'P.I.': 1,
 'Amen.': 1,
 'Truth': 3,
 'Charlie': 2,
 'Orange': 1,
 'County': 1,
 'Ronnie': 1,
 'Benjamins': 1,
 'Avenging': 1,
 'Angelo': 1,
 'FearDotCom': 1,
 'Air': 2,
 'Bud:': 2,
 'Seventh': 1,
 'Inning': 1,
 'Fetch': 1,
 'Wild': 6,
 'Thornberrys': 1,
 'Auto': 1,
 'Focus': 1,
 'Powerpuff': 1,
 'Girls': 7,
 'Buying': 1,
 'Cow': 1,
 'Bubba': 1,
 'Ho-tep': 1,
 'Possession': 1,
 'Evelyn': 1,
 'Juwanna': 1,
 'Mann': 1,
 'Full': 2,
 'Frontal': 1,
 'Repli-Kate': 1,
 'Hunter:': 1,
 'Collision': 1,
 'Course': 1,
 'Death': 3,
 'Smoochy': 1,
 'Trouble': 1,
 'Psycho': 3,
 'Kung': 1,
 'Pow:': 1,
 'Enter': 1,
 'Fist': 1,
 'Highway': 1,
 'Swimfan': 1,
 '2009': 1,
 'ë¡œìŠ¤íŠ¸ë©”ëª¨ë¦¬ì¦ˆ': 1,
 'Undercover': 1,
 'Brother': 2,
 'Left': 2,
 'Tribulation': 1,
 'Force': 1,
 'Below': 1,
 'Ted': 1,
 'Bundy': 1,
 'Riders': 1,
 'La': 4,
 'Mancha': 1,
 'Morvern': 1,
 'Callar': 1,
 'Ã”nibus': 1,
 '174': 1,
 'fils': 1,
 'Tuck': 1,
 'Everlasting': 1,
 'Roger': 1,
 'Dodger': 1,
 'lunes': 1,
 'al': 1,
 'sol': 1,
 'Bang': 4,
 "You're": 1,
 'Carpenterâ€™s': 1,
 'Vampires:': 1,
 'Muertos': 1,
 'Stealing': 1,
 'Harvard': 1,
 '3': 5,
 'zÃ©ros': 1,
 'Plots': 1,
 'View': 2,
 'Century': 1,
 'Self': 1,
 'Master': 2,
 'Disguise': 1,
 'Sixteen': 1,
 'Deuces': 1,
 'Inuyasha:': 1,
 'Kagami': 1,
 'no': 3,
 'Naka': 1,
 'MugenjÅ': 1,
 'VeggieTales:': 1,
 'Jonah': 1,
 '4:': 2,
 'Prophecy': 1,
 'Fulfilled': 1,
 'Kid': 4,
 'Stays': 1,
 'Picture': 1,
 'Underworld': 1,
 'Pirates': 1,
 'Caribbean:': 1,
 'Kill': 2,
 'Bill:': 2,
 'Vol.': 2,
 '1': 3,
 'Matrix': 2,
 'Revolutions': 1,
 'Reloaded': 1,
 'Finding': 3,
 'Nemo': 1,
 'Bruce': 1,
 'Almighty': 1,
 'Actually': 1,
 'Elf': 1,
 'Terminator': 1,
 'Rise': 3,
 'Machines': 1,
 'Dreamers': 1,
 'Fish': 1,
 'Daredevil': 1,
 'League': 1,
 'Extraordinary': 1,
 'Gentlemen': 1,
 'Italian': 1,
 'Job': 1,
 'Jungle': 2,
 'Book': 3,
 'Translation': 1,
 'Johnny': 1,
 'English': 1,
 'Bear': 1,
 'Peter': 2,
 'Pan': 1,
 'Honey': 1,
 'Apart': 1,
 'School': 4,
 'Samurai': 1,
 'Croft': 1,
 'Raider:': 1,
 'Cradle': 2,
 'Wrong': 1,
 'Turn': 1,
 'Commander:': 1,
 'Side': 1,
 'Mona': 2,
 'Lisa': 1,
 'Smile': 1,
 'Mystic': 1,
 'River': 1,
 'Animatrix': 1,
 'Anger': 2,
 'Management': 1,
 'Core': 1,
 'Hulk': 1,
 'Once': 1,
 'Upon': 2,
 'Mexico': 1,
 '101': 1,
 'Dalmatians': 2,
 "Patch's": 1,
 'London': 4,
 'Old': 2,
 'Lose': 1,
 '10': 1,
 'Shanghai': 2,
 'Knights': 1,
 'S.W.A.T.': 1,
 'Tears': 1,
 'Red,': 1,
 "Milo's": 1,
 'Cat': 1,
 'Hat': 1,
 'Freaky': 1,
 'Sinbad:': 1,
 'Seven': 1,
 'Seas': 1,
 'Timeline': 1,
 'Paycheck': 1,
 "Charlie's": 2,
 'Angels:': 1,
 'Throttle': 1,
 "Something's": 1,
 'Gotta': 1,
 'Give': 1,
 'Mansion': 1,
 'Duplex': 1,
 'Gothika': 1,
 '21': 1,
 'Grams': 1,
 'Destination': 3,
 'George': 2,
 'Chainsaw': 1,
 'Massacre': 1,
 'Recruit': 1,
 'Cheaper': 2,
 'Dozen': 2,
 'Mountain': 2,
 '11:14': 1,
 'Holes': 1,
 'Medallion': 1,
 'Thirteen': 2,
 'Grave': 2,
 "Boundin'": 1,
 'Looney': 1,
 'Tunes:': 1,
 'Action': 1,
 'Basic': 1,
 'Rundown': 1,
 'Swan': 1,
 'Lake': 1,
 'Top': 2,
 'Batman:': 2,
 'Mystery': 1,
 'Batwoman': 1,
 'Confidence': 1,
 'What': 6,
 'Wants': 1,
 'Open': 2,
 'Range': 2,
 'Married': 1,
 'Under': 2,
 'Tuscan': 1,
 'Tais-toi': 1,
 '!': 1,
 'Daddy': 1,
 'Care': 1,
 'Matchstick': 1,
 'Seabiscuit': 1,
 'Lizzie': 1,
 'McGuire': 1,
 'Dreamcatcher': 1,
 'Bionicle:': 1,
 'Mask': 2,
 'Light': 1,
 'Ned': 1,
 'Bulletproof': 1,
 'Monk': 1,
 '3-D:': 1,
 'Intolerable': 1,
 'Cruelty': 1,
 'Hunted': 1,
 'Sand': 1,
 'Fog': 3,
 'Stitch!': 1,
 'Divorce': 1,
 'Lampoon': 1,
 'Presents': 2,
 'Dorm': 1,
 'Daze': 1,
 ...}

In [40]:
total_no_words=sum(number_of_words.values())
print("total number of words used :",total_no_words)
distinct_no_words=len(number_of_words.keys())
print("total number of distinct words :",distinct_no_words)

total number of words used : 4196
total number of distinct words : 2226

In [41]:
average_number_of_words=total_no_words/distinct_no_words
print("the average number of words in movie titles between the year 2000-2005 :",average_number_of_words)

the average number of words in movie titles between the year 2000-2005 : 1.884995507637017